[[redirects]]
  from = "/api/*"
  to = "http://103.80.163.237:5051/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/deepfake/*"
  to = "/deepfake/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
